name:                htwit
version:             0.1.0.0
github:              "pfcm/htwit"
license:             BSD3
author:              "Author name here"
maintainer:          "pfcm@pfcmathews.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:          Short description of your package
# category:          Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pfcm/htwit#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - text
  - twitter-conduit
  - conduit
  - twitter-types-lens
  - twitter-types
  - authenticate-oauth
  - optparse-applicative
  - lens
  - lens-aeson
  - directory

library:
  source-dirs:       src

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wredundant-constraints

executables:
  search-tweets:
    main:            SearchMain.hs
    source-dirs:     app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is SearchMain
    dependencies:
    - htwit
  filter-statuses:
    main:            FilterMain.hs
    source-dirs:     app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is FilterMain
    dependencies:
    - htwit

tests:
  htwit-test:
    main:            Spec.hs
    source-dirs:     test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - htwit
